### PR TITLE
[Fix for-GET/katt#26] Use include instead of include_lib…

### PR DESCRIPTION
**Pull request by elbrujohalcon**
…to keep @gadgetci at ease

### CODE REVIEW

**Comment by andreineculau** [comment]
ping @isakb --- is your memory good enough? I do remember a couple of hickups with include_lib/include in the Klarna setup

**Comment by andreineculau** [comment]
@elbrujohalcon Thanks for looking into this!

**Comment by isakb** [comment]
I think it was just someone more experienced who complained in a code
review.

This change looks sane to me.

"include_lib is similar to include, but is not to point out an absolute
file. Instead, the first path component (possibly after variable
substitution) is assumed to be the name of an application."

**Comment by andreineculau** [comment]
Thank you both!

**Comment by elbrujohalcon** [comment]
:+1: 

…and stay tuned… @euen is working on the next version of Gadget where you'll no longer need us to debug this misteries (hopefully).

**Pull request merged**
