### PR TITLE
try to fix inaka gadget hooks

### PR DESCRIPTION
**Pull request by andreineculau**

### CODE REVIEW

**Comment by andreineculau** [comment]
@elbrujohalcon can you help out on why `gadget/compiler` and `gadget/xref` fail with this cryptic `2` code? I have removed `gadget/dialyzer` at least, since it's only compatible with erlang.mk. Thanks a bunch!

**Comment by elbrujohalcon** [comment]
I'm on vacation, but @euen is working precisely on that these days

**Comment by elbrujohalcon** [comment]
I just realized that @euen will be on vacation too this week. Hopefully, @harenson can take a look at the server logs... And once @euen is done you will have a page to see the errors yourself :)

**Comment by andreineculau** [comment]
Thank you. Now enjoy your vacation, Bruno :) This can wait

On Sun, Jan 31, 2016 at 5:35 AM, Brujo Benavides <notifications@github.com>
wrote:

> I just realized that @euen <https://github.com/euen> will be on vacation
> too this week. Hopefully, @harenson <https://github.com/harenson> can
> take a look at the server logs... And once @euen <https://github.com/euen>
> is done you will have a page to see the errors yourself :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/for-GET/katt/pull/26#issuecomment-177388678>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by harenson** [comment]
@andreineculau Hi, please come along and join us on our public [HipChat](http://inaka.net/hipchat) channel and ping me so I can help you.

**Comment by andreineculau** [comment]
@elbrujohalcon take it easy on your vacation, but when you're back, please have a look at this yourself ;) thanks!

**Comment by elbrujohalcon** [comment]
@andreineculau let's start checking…

- [ ] compiler : I still don't know
- [x] dialyzer: you should not use gadget's dialyzer in not-erlang.mk-based projects
- [ ] xref: Stay tuned…

**Comment by elbrujohalcon** [comment]
@andreineculau I found the issue!
The whole problem is that the folder in which gadget clones your repo is not called `katt` and you are using the fact that you're on a folder called `katt` while compiling your project in [this line](https://github.com/for-GET/katt/blob/develop/priv/katt_blueprint.peg#L287):

```erlang
-include_lib("katt/include/blueprint_types.hrl").
```

Any particular reason for using `include_lib` instead of `include` there?

**Comment by elbrujohalcon** [comment]
BTW, @andreineculau … I changed that line to
```erlang
-include("blueprint_types.hrl").
```
and gadget had no more issues (check inaka/katt#1).

I tried to run `make test` with and without the change in several tests failed in both cases (always the same tests, which is _comforting_)

**Pull request merged**
