### PR TITLE
Add custom function validation

### PR DESCRIPTION
**Pull request by erikgustafson-klarna**
This PR allows using user defined functions for validating and reading values from JSON fields.

### CODE REVIEW

**Comment by andreineculau** [comment]
I'm sorry but I'm going to reject this PR.
A major advantage of KATT is that the scenarios (aka blueprints) are language-abstract.

That said, you can do what you want without any change in KATT by introducing a new validation type e.g.

```
{
  "type": "klarna_erlang",
  "erl_eval": "some_module:some_validation_fun(arg1, arg2)"
}
```

```erl
KlarnaJson =
  fun(recall_body) ->
    [ fun katt_callbacks_json:recall_body/4
    ];
  fun(parse) ->
    [ fun katt_callbacks_json:parse/5
    ];
  fun(validate_body) ->
    [ fun katt_callbacks_json:validate_body/3
    ],
  fun(validate_type) ->
    [ fun katt_callbacks_json:validate_type/7
    , fun klarna_callbacks_json:validate_type/7
    ],
katt:run("klarna_erlang_scenario.apib", [], [{ext, KlarnaJson}]).
```

where

`klarna_callbacks_json:validate_type/7` is basically like https://github.com/for-GET/katt/blob/master/src/katt_callbacks_json.erl#L98 but not for the "klarna_erlang" type, with your code from https://github.com/for-GET/katt/pull/29/files#diff-0ca8b609d9263432236ebef8184c89c0R489

**Comment by andreineculau** [comment]
Out of curiousity, what type of validation are you doing in your custom funs? i.e. what validation is not supported by KATT today?

**Comment by erikgustafson-klarna** [comment]
Okay,

Regards  Erik

**Comment by erikgustafson-klarna** [comment]
There are 3 things we need to do

1. Making sure that a list contains at least some elements regardless of
order.

2. Making sure that a JSON structure like this one

[
   {type:"elv"},
   {type:"invoice"},
   .....
]

contains at least elements with type elv and invoice. Order in this case is
unknown and extra elements could be present

3. Using regex to pick out values from a string to store for use further
down in the test

// Erik

**Comment by andreineculau** [comment]
1. Already supported, that's why we introduced the "set" validation type e.g. https://github.com/for-GET/katt/blob/master/test/katt_run_validate_type_set_tests.erl#L162

2. don't see how this is different than 1. All structures accept unknown elements, unless `{{unexpected}}` is given.

3. also already supported https://github.com/for-GET/katt/blob/master/test/katt_run_tests.erl#L449

**Comment by erikgustafson-klarna** [comment]
Cool, we are still running on a pretty old version of katt internally in
Klarna and the set feature was not  included in that


Thanks for your time

**Comment by sstrigler** [comment]
This use case rings a bell, a thing I wanted to take care of a while ago. :(

**Comment by sstrigler** [comment]
Ah m)

**Pull request closed without merging**
